//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchangeAccountingApp.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExchangeRates()
        {
            this.Currencies = new HashSet<Currencies>();
        }
    
        public int Rate_ID { get; set; }
        public int Currency_ID { get; set; }
        public decimal Buy_Rate { get; set; }
        public decimal Sell_Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currencies> Currencies { get; set; }
    }
}
