//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchangeAccountingApp.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int Operation_ID { get; set; }
        public Nullable<int> User_ID_Correct { get; set; }
        public int User_ID { get; set; }
        public int Client_ID { get; set; }
        public int Currency_ID_From { get; set; }
        public int Currency_ID_To { get; set; }
        public decimal Amount_From { get; set; }
        public string Currency_Name_From { get; set; }
        public decimal Amount_To { get; set; }
        public string Currency_Name_To { get; set; }
        public System.DateTime Operation_Date { get; set; }
        public Nullable<System.DateTime> Last_Update_Date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual Currencies Currencies1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
